#!/bin/bash
# Build platform-specific Blender extension bundles with ML models
#
# This script:
# 1. Converts MedSAM2 models (MLX for macOS, ONNX for Windows/Linux)
# 2. Copies models to extension/ml/ folder
# 3. Builds extension with Blender
# 4. Creates platform-specific variants (macOS, Windows, Linux)
#
# Usage:
#   ./build_extension.sh [--skip-conversion] [--blender-path /path/to/blender]

set -e

# ============================================================
# Configuration
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODELS_DIR="$SCRIPT_DIR/models"
EXTENSION_DIR="$SCRIPT_DIR/extension"
BUILD_DIR="$SCRIPT_DIR/build"
DIST_DIR="$SCRIPT_DIR/dist"

# Default Blender path (can be overridden)
BLENDER_PATH="${BLENDER_PATH:-/Applications/Blender.app/Contents/MacOS/Blender}"

# Parse arguments
SKIP_CONVERSION=false
while [[ $# -gt 0 ]]; do
    case $1 in
        --skip-conversion)
            SKIP_CONVERSION=true
            shift
            ;;
        --blender-path)
            BLENDER_PATH="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--skip-conversion] [--blender-path /path/to/blender]"
            exit 1
            ;;
    esac
done

# ============================================================
# Helper Functions
# ============================================================

print_header() {
    echo ""
    echo "============================================================"
    echo "$1"
    echo "============================================================"
}

print_step() {
    echo ""
    echo "--- $1 ---"
}

check_blender() {
    if [ ! -f "$BLENDER_PATH" ]; then
        echo "ERROR: Blender not found at: $BLENDER_PATH"
        echo "Set BLENDER_PATH environment variable or use --blender-path"
        exit 1
    fi
    echo "✓ Found Blender: $BLENDER_PATH"
}

# ============================================================
# Main Build Process
# ============================================================

print_header "Blender Extension Builder"
echo "Building platform-specific bundles with ML models"

# Step 1: Check Blender
print_step "Checking Blender"
check_blender

# Step 2: Convert models (optional)
if [ "$SKIP_CONVERSION" = false ]; then
    print_step "Converting MedSAM2 Models"
    
    # Check if conversion script exists
    CONVERT_SCRIPT="$SCRIPT_DIR/convert_medsam2.py"
    if [ ! -f "$CONVERT_SCRIPT" ]; then
        echo "ERROR: Conversion script not found: $CONVERT_SCRIPT"
        echo "Please add the convert_medsam2.py script to the project root"
        echo "Or use --skip-conversion if models are already in extension/ml/"
        exit 1
    fi
    
    # Check if conversion environment exists
    if [ ! -d "$MODELS_DIR/.venv" ]; then
        echo "Setting up conversion environment..."
        echo "Creating Python virtual environment..."
        mkdir -p "$MODELS_DIR"
        python3 -m venv "$MODELS_DIR/.venv"
        source "$MODELS_DIR/.venv/bin/activate"
        pip install --upgrade pip
        pip install torch torchvision numpy pillow safetensors mlx onnx onnxruntime
        echo "✓ Conversion environment created"
    else
        echo "✓ Conversion environment exists"
        source "$MODELS_DIR/.venv/bin/activate"
    fi
    
    # Check if sam2_repo exists
    SAM2_REPO="$MODELS_DIR/.cache/sam2_repo"
    if [ ! -d "$SAM2_REPO" ]; then
        echo "Cloning SAM2 repository..."
        mkdir -p "$MODELS_DIR/.cache"
        git clone https://github.com/facebookresearch/segment-anything-2.git "$SAM2_REPO"
        echo "✓ SAM2 repository cloned"
    else
        echo "✓ SAM2 repository exists"
    fi
    
    # Run conversion (should output to extension/ml/medsam2_mlx/ and extension/ml/medsam2_onnx/)
    echo "Running conversion script..."
    echo "Output will be in extension/ml/medsam2_mlx/ and extension/ml/medsam2_onnx/"
    python "$CONVERT_SCRIPT"
    
    deactivate
    
    echo "✓ Models converted"
else
    print_step "Skipping Model Conversion"
    echo "Using existing models in extension/ml/"
fi

# Step 3: Verify models exist
print_step "Verifying Models"

# Models are in extension/ml/ (either pre-existing or generated by CI/CD)
MLX_WEIGHTS="$EXTENSION_DIR/ml/medsam2_mlx/weights.safetensors"
MLX_CONFIG="$EXTENSION_DIR/ml/medsam2_mlx/model_config.json"
ONNX_ENCODER="$EXTENSION_DIR/ml/medsam2_onnx/encoder.onnx"
ONNX_DECODER="$EXTENSION_DIR/ml/medsam2_onnx/decoder.onnx"

MISSING_MODELS=false

if [ ! -f "$MLX_WEIGHTS" ] || [ ! -f "$MLX_CONFIG" ]; then
    echo "ERROR: MLX model not found:"
    echo "  Expected: $MLX_WEIGHTS"
    echo "  Expected: $MLX_CONFIG"
    MISSING_MODELS=true
fi

if [ ! -f "$ONNX_ENCODER" ] || [ ! -f "$ONNX_DECODER" ]; then
    echo "ERROR: ONNX models not found:"
    echo "  Expected: $ONNX_ENCODER"
    echo "  Expected: $ONNX_DECODER"
    MISSING_MODELS=true
fi

if [ "$MISSING_MODELS" = true ]; then
    echo ""
    echo "Models should be in extension/ml/medsam2_mlx/ and extension/ml/medsam2_onnx/"
    echo "Either:"
    echo "  1. Run conversion script to generate them"
    echo "  2. Download pre-converted models from CI/CD artifacts"
    exit 1
fi

echo "✓ MLX model: $(du -h "$MLX_WEIGHTS" | cut -f1)"
echo "✓ ONNX encoder: $(du -h "$ONNX_ENCODER" | cut -f1)"
echo "✓ ONNX decoder: $(du -h "$ONNX_DECODER" | cut -f1)"

# Step 4: Models are ready
print_step "Models Ready"

# Models are already in extension/ml/medsam2_mlx/ and extension/ml/medsam2_onnx/
# They will be included in the platform-specific builds
echo "✓ MLX models ready in extension/ml/medsam2_mlx/"
echo "✓ ONNX models ready in extension/ml/medsam2_onnx/"

# Step 5: Build platform-specific extensions
print_step "Building Platform-Specific Extensions"

rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

echo "Running Blender extension build with --split-platforms..."
"$BLENDER_PATH" --command extension build \
    --split-platforms \
    --source-dir "$EXTENSION_DIR" \
    --output-dir "$BUILD_DIR"

# Find the generated platform-specific zip files
MACOS_ZIP=$(find "$BUILD_DIR" -name "*-macos_arm64.zip" -type f | head -n 1)
WINDOWS_ZIP=$(find "$BUILD_DIR" -name "*-windows_x64.zip" -type f | head -n 1)
LINUX_ZIP=$(find "$BUILD_DIR" -name "*-linux_x64.zip" -type f | head -n 1)

if [ -z "$MACOS_ZIP" ] || [ -z "$WINDOWS_ZIP" ] || [ -z "$LINUX_ZIP" ]; then
    echo "ERROR: Not all platform zips found in $BUILD_DIR"
    ls -la "$BUILD_DIR"
    exit 1
fi

echo "✓ Platform-specific extensions built"

# Step 6: Move to dist directory
print_step "Organizing Distribution"

rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"

# Move the platform-specific zips to dist
mv "$MACOS_ZIP" "$DIST_DIR/"
mv "$WINDOWS_ZIP" "$DIST_DIR/"
mv "$LINUX_ZIP" "$DIST_DIR/"

# Get final paths and sizes
MACOS_ZIP="$DIST_DIR/$(basename "$MACOS_ZIP")"
WINDOWS_ZIP="$DIST_DIR/$(basename "$WINDOWS_ZIP")"
LINUX_ZIP="$DIST_DIR/$(basename "$LINUX_ZIP")"

MACOS_SIZE=$(du -h "$MACOS_ZIP" | cut -f1)
WINDOWS_SIZE=$(du -h "$WINDOWS_ZIP" | cut -f1)
LINUX_SIZE=$(du -h "$LINUX_ZIP" | cut -f1)

echo "✓ macOS bundle:   $MACOS_SIZE"
echo "✓ Windows bundle: $WINDOWS_SIZE"
echo "✓ Linux bundle:   $LINUX_SIZE"

# Step 7: Cleanup
print_step "Cleanup"

# Models stay in extension/ml/ (gitignored, but needed for local builds)
# They are embedded in the platform-specific zips
echo "✓ Build artifacts cleaned (models remain in extension/ml/ for next build)"

# Step 8: Summary
print_header "BUILD COMPLETE"

echo ""
echo "Platform-specific bundles created in: $DIST_DIR"
echo ""
echo "  macOS (Apple Silicon):  $MACOS_SIZE (MLX backend)"
echo "  Windows (x64):          $WINDOWS_SIZE (ONNX backend)"
echo "  Linux (x64):            $LINUX_SIZE (ONNX backend)"
echo ""
echo "Backend selection:"
echo "  • macOS ARM64: MLX (Apple Metal GPU acceleration)"
echo "  • Windows/Linux: ONNX Runtime (CPU/GPU)"
echo ""
echo "To install:"
echo "  1. Open Blender"
echo "  2. Edit → Preferences → Extensions"
echo "  3. Click dropdown → Install from Disk"
echo "  4. Select the appropriate .zip for your platform"
