#!/bin/bash
# Build platform-specific Blender extension bundles — CI/GH Actions version.
#
# Expects models to already exist in extension/ml/medsam2_mlx/ and
# extension/ml/medsam2_onnx/ (generated by convert_medsam2_ci.py).
#
# After Blender --split-platforms creates the per-platform zips, this script
# repacks each zip to remove models that don't belong on that platform:
#   - macOS ARM64:  keep MLX, remove ONNX  (saves ~128 MB)
#   - Windows x64:  keep ONNX, remove MLX  (saves ~160 MB)
#   - Linux x64:    keep ONNX, remove MLX  (saves ~160 MB)
#
# Usage:
#   ./build_extension_ci.sh --blender-path /path/to/blender

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXTENSION_DIR="$SCRIPT_DIR/extension"
BUILD_DIR="$SCRIPT_DIR/build"
DIST_DIR="$SCRIPT_DIR/dist"

BLENDER_PATH="${BLENDER_PATH:-blender}"

while [[ $# -gt 0 ]]; do
    case $1 in
        --blender-path)
            BLENDER_PATH="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--blender-path /path/to/blender]"
            exit 1
            ;;
    esac
done

echo ""
echo "============================================================"
echo "Blender Extension Builder (CI)"
echo "============================================================"

# ── Verify models ───────────────────────────────────────────────────────────
echo ""
echo "--- Verifying Models ---"

MISSING=false
for f in \
    "$EXTENSION_DIR/ml/medsam2_mlx/weights.safetensors" \
    "$EXTENSION_DIR/ml/medsam2_mlx/model_config.json" \
    "$EXTENSION_DIR/ml/medsam2_onnx/encoder.onnx" \
    "$EXTENSION_DIR/ml/medsam2_onnx/decoder.onnx"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: Missing $f"
        MISSING=true
    fi
done

if [ "$MISSING" = true ]; then
    echo "Run convert_medsam2_ci.py first to generate models."
    exit 1
fi

echo "✓ All model files present"

# ── Build with Blender ──────────────────────────────────────────────────────
echo ""
echo "--- Building Platform-Specific Extensions ---"

rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

"$BLENDER_PATH" --background --command extension build \
    --split-platforms \
    --source-dir "$EXTENSION_DIR" \
    --output-dir "$BUILD_DIR"

echo ""
echo "Generated builds:"
ls -lh "$BUILD_DIR"/*.zip 2>/dev/null || true

# ── Repack: remove wrong models per platform ────────────────────────────────
echo ""
echo "--- Removing unnecessary models from platform zips ---"

MACOS_ZIP=$(find "$BUILD_DIR" -name "*macos*arm64*.zip" -type f | head -n 1)
WINDOWS_ZIP=$(find "$BUILD_DIR" -name "*windows*x64*.zip" -type f | head -n 1)
LINUX_ZIP=$(find "$BUILD_DIR" -name "*linux*x64*.zip" -type f | head -n 1)

if [ -z "$MACOS_ZIP" ] || [ -z "$WINDOWS_ZIP" ] || [ -z "$LINUX_ZIP" ]; then
    echo "ERROR: Not all platform zips found in $BUILD_DIR"
    ls -la "$BUILD_DIR"
    exit 1
fi

# macOS ARM64: remove ONNX models (uses MLX)
echo "macOS: removing ONNX models..."
zip -d "$MACOS_ZIP" "*/ml/medsam2_onnx/*" || true

# Windows x64: remove MLX models (uses ONNX)
echo "Windows: removing MLX models..."
zip -d "$WINDOWS_ZIP" "*/ml/medsam2_mlx/*" || true

# Linux x64: remove MLX models (uses ONNX)
echo "Linux: removing MLX models..."
zip -d "$LINUX_ZIP" "*/ml/medsam2_mlx/*" || true

# ── Move to dist ────────────────────────────────────────────────────────────
echo ""
echo "--- Organizing Distribution ---"

rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"

mv "$MACOS_ZIP" "$DIST_DIR/"
mv "$WINDOWS_ZIP" "$DIST_DIR/"
mv "$LINUX_ZIP" "$DIST_DIR/"

echo ""
echo "============================================================"
echo "BUILD COMPLETE"
echo "============================================================"
echo ""
echo "Platform-specific bundles in: $DIST_DIR"
for z in "$DIST_DIR"/*.zip; do
    echo "  $(basename "$z"): $(du -h "$z" | cut -f1)"
done
echo ""
echo "  macOS ARM64:    MLX backend only"
echo "  Windows x64:    ONNX backend only"
echo "  Linux x64:      ONNX backend only"
